name = "Alex Adewole"
pseudonym = "bizarre"
headline = "Human in Vancouver."

[programming]
bio = "I respect and enjoy the complexity of distributed systems & networking. I also have a knack for devops & the likes. I really wanna try out some embedded software stuff and flesh out my knowledge in ML."
github = "bizarre"