name = "Alex Adewole"
pseudonym = "bizarre"
headline = "Human in Vancouver."

[programming]
bio = "Interested in learning more about scale, robotics & anything low-level. All in all just a dude who likes to write code & build cool shit."
github = "bizarre"