[package]
name = "proc-macro"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
syn = "1.0.96"
quote = "1.0.18"
proc-macro2 = "1.0.39"
darling = "0.14.1"
toml = "0.5.9"

[lib]
proc-macro = true